tag seems to be working (#2)
* tag seems to be working

* add examples

diff --git a/.github/workflows/on_pr_main.yml b/.github/workflows/on_pr_main.yml
--- a/.github/workflows/on_pr_main.yml
+++ b/.github/workflows/on_pr_main.yml
@@ -29,3 +29,23 @@ jobs:
           python-version: ${{ steps.get-versions.outputs.python-version }}
           poetry-version: ${{ steps.get-versions.outputs.poetry-version }}
           working-directory: ${{ env.SOURCE_DIRECTORY }}
+
+  ci-successful:
+    name: CI successful
+    runs-on: ubuntu-latest
+    needs:
+      - python-lint-test
+    if: ${{ !cancelled() }}
+    steps:
+      - name: Check if all previous steps were successful
+        # Take all the job names in the needs list and pipes them to jq to ensure that each succeeded,
+        #  if all have succeeded this passes, if not it files.
+        run: |
+          result=$(echo '${{ toJson(needs) }}' | jq 'all(.[]; .result == "success")')
+          if [ "$result" = "true" ]; then
+            echo "All jobs succeeded."
+            exit 0
+          else
+            echo "One or more jobs failed."
+            exit 1
+          fi
